language: go
go:
- '1.7'
env:
- PATH=/home/travis/gopath/bin:$PATH
install:
- go get github.com/mattn/gom
- gom install
before_deploy:
- go get -v github.com/mitchellh/gox
- gox -output build/{{.OS}}_{{.Arch}}/{{.Dir}}
- cd build
- for osarch in * ; do cd $osarch && zip -r ../metrin-$osarch.zip . && cd ../ ; done
- cd ../
deploy:
  provider: releases
  api_key:
    secure: Ia9xswwI3t07DzG9/XFtnkCszssgKKst2NLHIwretyBB8p7B+Q1pfLR47s/ce8gj8gNk5hvYizuv+CbDwmk2yimEymDP+yql6fCT4KiwEFJwC+Ktz9FW5y9D7pUYnJTYTZdXpZYQKV1NNO4kqNVzVWfSxMtrPgsZ0/V8HWaStQQydBEr7fMVmR4CRtGjfm7TZ4kJmdTTGrumhmd087nIh8gOrlYVvg4uziHfiXAY4JY+RuUkuCaZkyTWuw1sgfAh0FXoP7D8Gx1OM/KoObZg4wIPgxotlK8LtFaznCShlPV7vuHTknib1tq12lQICHEehbKAfa5hw553m2f0ornedjMga30C8XTEZRQrUqmLftBOTKn4xovwtPOwjxHytlmcOFLkuZZS0ProqCzp+JIsD4RXQMg14q1ZdVJUD4A+v7xG3aXxIWjwryddVgZwsB9WaV15PF7MlwCln4abaZuQMJYC7CXE3mOg2Sb79ixJmBEOhzFaLZ9AHbldXyPltoWfADFyP9Q0R2pOhaltsTItJAP4LgNLcpvLtPtZ+13iYyrduMU5+aV8mlEopWqomcULD1THq3G4UR1idq7HD+17iXuXXziqmgfYmZr/tV3n86yFFujWmDE6khW2l6aza2NPTqlZdAbW+AjDd9jTDadL3KlkIDgnOoDduoEKXsirj0k=
  file:
  - build/metrin-darwin_386.zip
  - build/metrin-darwin_amd64.zip
  - build/metrin-freebsd_386.zip
  - build/metrin-freebsd_amd64.zip
  - build/metrin-freebsd_arm.zip
  - build/metrin-linux_386.zip
  - build/metrin-linux_amd64.zip
  - build/metrin-linux_arm.zip
  - build/metrin-netbsd_386.zip
  - build/metrin-netbsd_amd64.zip
  - build/metrin-netbsd_arm.zip
  - build/metrin-openbsd_386.zip
  - build/metrin-openbsd_amd64.zip
  - build/metrin-windows_386.zip
  - build/metrin-windows_amd64.zip
  skip_cleanup: true
  all_branches: true
  on:
    repo: y13i/metrin
    tags: true
